import Ionicons from '@expo/vector-icons/Ionicons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, View } from 'react-native';
import { PressableScale } from '@/components/pressable-scale';
import { ThemedText } from '@/components/themed-text';
import { requestLocationPermission, startLocationTracking } from '@/services/location-service';
import { spacing, shadow, useTraceTheme } from '@/theme';
export default function LocationPermission(){const router=useRouter();const {colors}=useTraceTheme();const [loading,setLoading]=useState(false);const request=async()=>{setLoading(true);try{if(process.env.EXPO_OS!=='web'&&await requestLocationPermission())await startLocationTracking({backgroundPreferred:false,requestPermission:false});}catch(error){console.error('Trace location onboarding request failed',error)}finally{setLoading(false);router.push('/onboarding/photos')}};return <ScrollView contentContainerStyle={[styles.content,{backgroundColor:colors.background}]}><View style={styles.hero}><View style={[styles.icon,{backgroundColor:colors.accentSoft}]}><Ionicons name="location-outline" size={34} color={colors.text}/></View><ThemedText variant="screenTitle">방문한 장소를 기억할 수 있도록</ThemedText><ThemedText variant="body" style={{color:colors.secondaryText}}>Trace는 일정 시간 머문 장소를 자동으로 기록합니다.{`\n`}앱을 열어두지 않아도 당신의 하루가 이어질 수 있어요.</ThemedText></View><View style={styles.actions}><PressableScale disabled={loading} onPress={()=>void request()} style={[styles.cta,{backgroundColor:colors.accent,boxShadow:shadow.cta}]}>{loading?<ActivityIndicator color={colors.onAccent}/>:<><ThemedText variant="headline" style={{color:colors.onAccent}}>위치 허용</ThemedText><Ionicons name="arrow-forward" size={17} color={colors.onAccent}/></>}</PressableScale><PressableScale disabled={loading} onPress={()=>router.push('/onboarding/photos')} style={styles.skip}><ThemedText variant="subhead" style={{color:colors.secondaryText}}>나중에</ThemedText></PressableScale></View></ScrollView>}
const styles=StyleSheet.create({content:{flexGrow:1,justifyContent:'space-between',padding:spacing.ml,paddingTop:96,paddingBottom:spacing.xxl,gap:spacing.xxl},hero:{gap:spacing.md},icon:{width:72,height:72,borderRadius:24,alignItems:'center',justifyContent:'center',marginBottom:spacing.sm},actions:{gap:spacing.xs},cta:{minHeight:56,borderRadius:18,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:spacing.xs},skip:{minHeight:48,alignItems:'center',justifyContent:'center'}});
