import Ionicons from '@expo/vector-icons/Ionicons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, View } from 'react-native';
import { PressableScale } from '@/components/pressable-scale';
import { ThemedText } from '@/components/themed-text';
import { requestPhotoPermission } from '@/services/photo-service';
import { spacing, shadow, useTraceTheme } from '@/theme';
export default function PhotoPermission(){const router=useRouter();const {colors}=useTraceTheme();const [loading,setLoading]=useState(false);const request=async()=>{setLoading(true);try{if(process.env.EXPO_OS!=='web')await requestPhotoPermission()}catch(error){console.error('Trace photo onboarding request failed',error)}finally{setLoading(false);router.push('/onboarding/ready')}};return <ScrollView contentContainerStyle={[styles.content,{backgroundColor:colors.background}]}><View style={styles.hero}><View style={[styles.icon,{backgroundColor:colors.lavender}]}><Ionicons name="images-outline" size={34} color={colors.text}/></View><ThemedText variant="screenTitle">그날의 사진을{`\n`}그날의 장소와 연결해요</ThemedText><ThemedText variant="body" style={{color:colors.secondaryText}}>방문했던 시간에 촬영한 사진을 찾아{`\n`}하나의 추억으로 만들어 드립니다.</ThemedText></View><View style={styles.actions}><PressableScale disabled={loading} onPress={()=>void request()} style={[styles.cta,{backgroundColor:colors.accent,boxShadow:shadow.cta}]}>{loading?<ActivityIndicator color={colors.onAccent}/>:<><ThemedText variant="headline" style={{color:colors.onAccent}}>사진 허용</ThemedText><Ionicons name="arrow-forward" size={17} color={colors.onAccent}/></>}</PressableScale><PressableScale disabled={loading} onPress={()=>router.push('/onboarding/ready')} style={styles.skip}><ThemedText variant="subhead" style={{color:colors.secondaryText}}>나중에</ThemedText></PressableScale></View></ScrollView>}
const styles=StyleSheet.create({content:{flexGrow:1,justifyContent:'space-between',padding:spacing.ml,paddingTop:96,paddingBottom:spacing.xxl,gap:spacing.xxl},hero:{gap:spacing.md},icon:{width:72,height:72,borderRadius:24,alignItems:'center',justifyContent:'center',marginBottom:spacing.sm},actions:{gap:spacing.xs},cta:{minHeight:56,borderRadius:18,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:spacing.xs},skip:{minHeight:48,alignItems:'center',justifyContent:'center'}});
