import Ionicons from '@expo/vector-icons/Ionicons';
import { useRouter } from 'expo-router';
import { ScrollView, StyleSheet, View } from 'react-native';
import { BrandLogo } from '@/components/brand-logo';
import { PressableScale } from '@/components/pressable-scale';
import { ThemedText } from '@/components/themed-text';
import { useAuthStore } from '@/store/auth-store';
import { radius, shadow, spacing, useTraceTheme } from '@/theme';
export default function ReadyScreen() { const router = useRouter(); const { colors } = useTraceTheme(); const completeOnboarding = useAuthStore((state) => state.completeOnboarding); const finish = async () => { await completeOnboarding(); router.replace('/(tabs)/home'); }; return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={[styles.content, { backgroundColor: colors.background }]}><View style={styles.body}><View style={[styles.visual, { backgroundColor: colors.journey, boxShadow: shadow.raised }]}><BrandLogo size={96} /><Ionicons name="sparkles" size={26} color="#C8B8F3" style={styles.sparkle} /></View><ThemedText variant="screenTitle">준비가 끝났어요.</ThemedText><ThemedText variant="body" style={{ color: colors.secondaryText }}>이제 Trace가 당신의 하루를 조용히 기록할게요.</ThemedText><View style={[styles.checklist, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.row}><Ionicons name="location" size={19} color={colors.success} /><ThemedText variant="body" style={styles.flex}>위치 기록</ThemedText><Ionicons name="checkmark-circle" size={20} color={colors.success} /></View><View style={styles.row}><Ionicons name="images" size={19} color={colors.warm} /><ThemedText variant="body" style={styles.flex}>사진 연결</ThemedText><Ionicons name="checkmark-circle" size={20} color={colors.success} /></View></View></View><PressableScale onPress={() => void finish()} style={[styles.cta, { backgroundColor: colors.accent, boxShadow: shadow.cta }]}><ThemedText variant="headline" style={{ color: colors.onAccent }}>내 Trace 열기</ThemedText><Ionicons name="arrow-forward" size={18} color={colors.onAccent} /></PressableScale></ScrollView>; }
const styles = StyleSheet.create({ content: { flexGrow: 1, padding: spacing.ml, paddingTop: spacing.lg, paddingBottom: spacing.xxl, justifyContent: 'space-between', gap: spacing.xl }, body: { gap: spacing.md }, visual: { height: 290, borderRadius: radius.lg, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.sm }, sparkle: { position: 'absolute', top: 54, right: 70 }, checklist: { borderRadius: radius.card, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: spacing.md }, row: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, flex: { flex: 1 }, cta: { minHeight: 56, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: spacing.xs } });
