import Ionicons from '@expo/vector-icons/Ionicons';
import { Redirect, useRouter } from 'expo-router';
import { ScrollView, StyleSheet, View } from 'react-native';
import { BrandLogo } from '@/components/brand-logo';
import { PressableScale } from '@/components/pressable-scale';
import { ThemedText } from '@/components/themed-text';
import { useAuthStore } from '@/store/auth-store';
import { spacing, useTraceTheme } from '@/theme';

export default function AuthScreen() {
  const router = useRouter(); const { colors } = useTraceTheme(); const signIn = useAuthStore((s) => s.signIn); const isLoading = useAuthStore((s) => s.isLoading); const error = useAuthStore((s) => s.error); const clearError = useAuthStore((s) => s.clearError); const authenticated = useAuthStore((s) => s.isAuthenticated); const onboardingCompleted = useAuthStore((s) => s.onboardingCompleted);
  const provider = (name: 'apple' | 'google') => { clearError(); void signIn(name).catch((cause) => console.error(`Trace ${name} mock sign-in failed`, cause)); };
  if (authenticated) return <Redirect href={onboardingCompleted ? '/(tabs)/home' : '/onboarding/permissions'} />;
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={[styles.content, { backgroundColor: colors.background }]}><View style={styles.container}><View style={styles.brand}><BrandLogo size={82} /><ThemedText variant="screenTitle">Trace</ThemedText></View><View style={styles.copy}><ThemedText variant="largeTitle" style={styles.center}>기억하지 않아도,{`\n`}당신의 하루는 남아 있습니다.</ThemedText><ThemedText variant="body" style={[styles.center, { color: colors.secondaryText }]}>방문한 장소와 그날의 사진을 연결해{`\n`}당신만의 시간을 자동으로 기록합니다.</ThemedText></View><View style={styles.actions}><PressableScale disabled={isLoading} onPress={() => provider('apple')} style={[styles.button, { backgroundColor: colors.text }]}><Ionicons name="logo-apple" size={21} color={colors.background} /><ThemedText variant="headline" style={{ color: colors.background }}>Apple로 계속하기</ThemedText></PressableScale><PressableScale disabled={isLoading} onPress={() => provider('google')} style={[styles.button, { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1 }]}><Ionicons name="logo-google" size={20} color={colors.text} /><ThemedText variant="headline">Google로 계속하기</ThemedText></PressableScale><View style={styles.divider}><View style={[styles.rule, { backgroundColor: colors.border }]} /><ThemedText variant="caption" style={{ color: colors.tertiaryText }}>또는</ThemedText><View style={[styles.rule, { backgroundColor: colors.border }]} /></View><PressableScale disabled={isLoading} onPress={() => router.push('/email-login')} style={[styles.button, { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1 }]}><Ionicons name="mail-outline" size={20} color={colors.text} /><ThemedText variant="headline">이메일로 계속하기</ThemedText></PressableScale>{error ? <ThemedText variant="caption" style={[styles.center, { color: colors.warm }]}>{error}</ThemedText> : null}<PressableScale onPress={() => router.push('/signup')} style={styles.signup}><ThemedText variant="subhead" style={{ color: colors.secondaryText }}>처음이신가요?</ThemedText><ThemedText variant="headline">회원가입</ThemedText></PressableScale></View><View style={styles.footer}><ThemedText variant="caption" style={{ color: colors.tertiaryText }}>개인정보처리방침</ThemedText><ThemedText variant="caption" style={{ color: colors.tertiaryText }}>이용약관</ThemedText></View></View></ScrollView>;
}
const styles = StyleSheet.create({ content: { flexGrow: 1, paddingHorizontal: spacing.lg, paddingVertical: spacing.xl }, container: { width: '100%', maxWidth: 380, alignSelf: 'center', flexGrow: 1, justifyContent: 'center', gap: spacing.xl }, brand: { alignItems: 'center', gap: spacing.sm }, copy: { gap: spacing.md }, center: { textAlign: 'center' }, actions: { gap: spacing.sm }, button: { minHeight: 52, borderRadius: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm }, divider: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginVertical: spacing.xs }, rule: { height: 1, flex: 1 }, signup: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs, marginTop: spacing.xs }, footer: { flexDirection: 'row', justifyContent: 'center', gap: spacing.lg, paddingTop: spacing.md } });
