import Ionicons from '@expo/vector-icons/Ionicons';
import { Stack, useRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { PressableScale } from '@/components/pressable-scale';
import { ThemedText } from '@/components/themed-text';
import { useAuthStore } from '@/store/auth-store';
import { radius, spacing, typography, useTraceTheme } from '@/theme';
const pattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export default function EmailLogin(){const router=useRouter();const {colors}=useTraceTheme();const signIn=useAuthStore(s=>s.signIn);const loading=useAuthStore(s=>s.isLoading);const serviceError=useAuthStore(s=>s.error);const clearError=useAuthStore(s=>s.clearError);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [visible,setVisible]=useState(false);const [error,setError]=useState<string|null>(null);const submit=async()=>{const e=!pattern.test(email.trim())?'이메일 주소를 확인해주세요.':password.length<8?'비밀번호는 8자 이상 입력해주세요.':null;setError(e);clearError();if(e)return;try{await signIn('email',{email:email.trim(),password})}catch(cause){console.error('Trace email login failed',cause)}};return <KeyboardAvoidingView style={[styles.root,{backgroundColor:colors.background}]} behavior={process.env.EXPO_OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Stack.Screen options={{title:'이메일 로그인'}}/><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color={colors.text}/></Pressable><View style={styles.header}><ThemedText variant="largeTitle">이메일로 계속하기</ThemedText><ThemedText variant="subhead" style={{color:colors.secondaryText}}>Trace 계정으로 기록을 이어가세요.</ThemedText></View><View style={styles.form}><View style={[styles.input,{backgroundColor:colors.surface}]}><Ionicons name="mail-outline" size={19} color={colors.secondaryText}/><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="이메일" placeholderTextColor={colors.tertiaryText} style={[styles.field,typography.body,{color:colors.text}]}/></View><View style={[styles.input,{backgroundColor:colors.surface}]}><Ionicons name="lock-closed-outline" size={19} color={colors.secondaryText}/><TextInput value={password} onChangeText={setPassword} secureTextEntry={!visible} placeholder="비밀번호" placeholderTextColor={colors.tertiaryText} style={[styles.field,typography.body,{color:colors.text}]}/><PressableScale onPress={()=>setVisible(v=>!v)}><Ionicons name={visible?'eye-off-outline':'eye-outline'} size={20} color={colors.secondaryText}/></PressableScale></View>{error||serviceError?<ThemedText variant="caption" style={{color:colors.warm}}>{error??serviceError}</ThemedText>:null}<PressableScale disabled={loading} onPress={()=>void submit()} style={[styles.cta,{backgroundColor:colors.accent}]}>{loading?<ActivityIndicator color={colors.onAccent}/>:<ThemedText variant="headline" style={{color:colors.onAccent}}>로그인</ThemedText>}</PressableScale><PressableScale onPress={()=>router.push('/signup')}><ThemedText variant="subhead" style={{textAlign:'center'}}>처음이신가요? 회원가입</ThemedText></PressableScale><PressableScale onPress={()=>router.push('/forgot-password')}><ThemedText variant="caption" style={{textAlign:'center',color:colors.secondaryText}}>비밀번호를 잊으셨나요?</ThemedText></PressableScale></View></ScrollView></KeyboardAvoidingView>}
const styles=StyleSheet.create({root:{flex:1},content:{flexGrow:1,padding:spacing.ml,paddingTop:spacing.xl,gap:spacing.xl},header:{gap:spacing.sm},form:{gap:spacing.sm},input:{minHeight:56,borderRadius:radius.md,paddingHorizontal:spacing.md,flexDirection:'row',alignItems:'center',gap:spacing.sm},field:{flex:1,paddingVertical:spacing.md},cta:{minHeight:54,borderRadius:18,alignItems:'center',justifyContent:'center'}});
