import Ionicons from '@expo/vector-icons/Ionicons';
import { Stack, useRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { PressableScale } from '@/components/pressable-scale';
import { ThemedText } from '@/components/themed-text';
import { resetPasswordForEmail } from '@/services/auth-service';
import { radius, spacing, typography, useTraceTheme } from '@/theme';
const pattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export default function ForgotPassword(){const router=useRouter();const {colors}=useTraceTheme();const [email,setEmail]=useState('');const [message,setMessage]=useState<string|null>(null);const [loading,setLoading]=useState(false);const submit=async()=>{if(!pattern.test(email.trim())){setMessage('이메일 주소를 확인해주세요.');return}setLoading(true);setMessage(null);try{await resetPasswordForEmail(email.trim());setMessage('비밀번호 재설정 링크를 보냈어요. 이메일을 확인해주세요.')}catch(cause){console.error('Trace password reset failed',cause);setMessage(cause instanceof Error?cause.message:'비밀번호 재설정 메일을 보내지 못했어요.')}finally{setLoading(false)}};return <KeyboardAvoidingView style={[styles.root,{backgroundColor:colors.background}]} behavior={process.env.EXPO_OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.content}><Stack.Screen options={{title:'비밀번호 찾기'}}/><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color={colors.text}/></Pressable><View style={styles.header}><ThemedText variant="largeTitle">비밀번호 찾기</ThemedText><ThemedText variant="subhead" style={{color:colors.secondaryText}}>가입한 이메일로 재설정 링크를 보내드릴게요.</ThemedText></View><View style={styles.form}><View style={[styles.input,{backgroundColor:colors.surface}]}><Ionicons name="mail-outline" size={19} color={colors.secondaryText}/><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="이메일" placeholderTextColor={colors.tertiaryText} style={[styles.field,typography.body,{color:colors.text}]}/></View>{message?<ThemedText variant="caption" style={{color:message.includes('보냈어요')?colors.success:colors.warm}}>{message}</ThemedText>:null}<PressableScale disabled={loading} onPress={()=>void submit()} style={[styles.cta,{backgroundColor:colors.accent}]}>{loading?<ActivityIndicator color={colors.onAccent}/>:<ThemedText variant="headline" style={{color:colors.onAccent}}>재설정 링크 보내기</ThemedText>}</PressableScale></View></ScrollView></KeyboardAvoidingView>}
const styles=StyleSheet.create({root:{flex:1},content:{flexGrow:1,padding:spacing.ml,paddingTop:spacing.xl,gap:spacing.xl},header:{gap:spacing.sm},form:{gap:spacing.sm},input:{minHeight:56,borderRadius:radius.md,paddingHorizontal:spacing.md,flexDirection:'row',alignItems:'center',gap:spacing.sm},field:{flex:1,paddingVertical:spacing.md},cta:{minHeight:54,borderRadius:18,alignItems:'center',justifyContent:'center'}});
