import Ionicons from '@expo/vector-icons/Ionicons';
import { Stack, useRouter } from 'expo-router';
import { useMemo } from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';
import { PressableScale } from '@/components/pressable-scale';
import { ThemedText } from '@/components/themed-text';
import { useAppStore } from '@/store/app-store';
import { radius, spacing, useTraceTheme } from '@/theme';
import { trips } from '@/services/mock-trips';

type Notice = { id: string; title: string; body: string; date: string; icon: keyof typeof Ionicons.glyphMap; target?: { pathname: '/memory/[id]'; id: string } | { pathname: '/review/[year]'; year: string } };
export default function NotificationsScreen() {
  const router = useRouter(); const { colors } = useTraceTheme(); const memories=useAppStore(s=>s.memories); const places=useAppStore(s=>s.places);
  const notices=useMemo<Notice[]>(()=>{ const today=new Date(); const rows:Notice[]=[]; memories.slice(0,5).forEach(m=>{const p=places.find(x=>x.id===m.placeId); rows.push({id:`memory-${m.id}`,title:'새로운 Memory가 만들어졌어요',body:`${p?.name??m.title}의 방문과 사진을 기록했어요.`,date:m.createdAt,icon:'sparkles-outline',target:{pathname:'/memory/[id]',id:m.id}})}); trips.slice(0,2).forEach(t=>rows.push({id:`trip-${t.id}`,title:'여행 기록을 발견했어요',body:`${t.title} · ${t.placeIds.length}곳이 연결되었어요.`,date:t.endedAt,icon:'airplane-outline',target:t.memoryIds[0]?{pathname:'/memory/[id]',id:t.memoryIds[0]}:undefined})); const yearAgo=memories.find(m=>{const d=new Date(m.startedAt);const target=new Date(today);target.setFullYear(target.getFullYear()-1);return d.toDateString()===target.toDateString()}); if(yearAgo)rows.push({id:'year-ago',title:'1년 전 오늘의 Memory',body:'그날의 기록을 다시 만나보세요.',date:yearAgo.startedAt,icon:'time-outline',target:{pathname:'/memory/[id]',id:yearAgo.id}}); rows.push({id:'monthly',title:'이번 달 Trace가 준비되었어요',body:'이번 달의 장소와 사진을 돌아보세요.',date:today.toISOString(),icon:'calendar-outline',target:{pathname:'/review/[year]',year:String(today.getFullYear())}}); return rows.sort((a,b)=>b.date.localeCompare(a.date)); },[memories,places]);
  const open=(notice:Notice)=>{if(!notice.target)return; const t=notice.target; router.push(t.pathname==='/memory/[id]'?{pathname:t.pathname,params:{id:t.id!}}:{pathname:t.pathname,params:{year:t.year!}})};
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={[styles.content,{backgroundColor:colors.background}]}><Stack.Screen options={{title:'알림'}}/><ThemedText variant="largeTitle">알림</ThemedText><ThemedText variant="subhead" style={{color:colors.secondaryText}}>Trace가 발견한 새로운 기록을 모아두었어요.</ThemedText><ThemedText variant="headline" style={styles.section}>오늘</ThemedText>{notices.filter(n=>new Date(n.date).toDateString()===new Date().toDateString()).map(n=><NoticeRow key={n.id} notice={n} colors={colors} onPress={()=>open(n)}/>)}<ThemedText variant="headline" style={styles.section}>이전 알림</ThemedText>{notices.filter(n=>new Date(n.date).toDateString()!==new Date().toDateString()).map(n=><NoticeRow key={n.id} notice={n} colors={colors} onPress={()=>open(n)}/>)}</ScrollView>;
}
function NoticeRow({notice,colors,onPress}:{notice:Notice;colors:ReturnType<typeof useTraceTheme>['colors'];onPress:()=>void}){return <PressableScale onPress={onPress} style={[styles.row,{backgroundColor:colors.surface}]}><View style={[styles.icon,{backgroundColor:colors.accentSoft}]}><Ionicons name={notice.icon} size={20} color={colors.text}/></View><View style={styles.copy}><ThemedText variant="headline">{notice.title}</ThemedText><ThemedText variant="caption" style={{color:colors.secondaryText}}>{notice.body}</ThemedText><ThemedText variant="caption" style={{color:colors.tertiaryText}}>{new Date(notice.date).toLocaleDateString('ko-KR')}</ThemedText></View><Ionicons name="chevron-forward" size={18} color={colors.tertiaryText}/></PressableScale>}
const styles=StyleSheet.create({content:{padding:spacing.ml,paddingBottom:spacing.xxxl,gap:spacing.sm},section:{marginTop:spacing.lg,marginBottom:spacing.xs},row:{padding:spacing.md,borderRadius:radius.md,flexDirection:'row',alignItems:'center',gap:spacing.md,marginBottom:spacing.xs},icon:{width:42,height:42,borderRadius:radius.full,alignItems:'center',justifyContent:'center'},copy:{flex:1,gap:3}});
