import Ionicons from '@expo/vector-icons/Ionicons';
import { Stack } from 'expo-router';
import { Alert, ScrollView, StyleSheet, View } from 'react-native';
import { PressableScale } from '@/components/pressable-scale';
import { ThemedText } from '@/components/themed-text';
import { useAppStore } from '@/store/app-store';
import { radius, spacing, useTraceTheme } from '@/theme';
export default function TrashScreen(){const {colors}=useTraceTheme();const deletedMemories=useAppStore(s=>s.deletedMemories);const deletedVisits=useAppStore(s=>s.deletedVisits);const restoreMemory=useAppStore(s=>s.restoreMemory);const restoreVisit=useAppStore(s=>s.restoreVisit);const permanentlyDeleteMemory=useAppStore(s=>s.permanentlyDeleteMemory);const permanentlyDeleteVisit=useAppStore(s=>s.permanentlyDeleteVisit);const confirm=(label:string,action:()=>void)=>Alert.alert('영구 삭제',`${label}을(를) 영구적으로 삭제할까요?`,[{text:'취소',style:'cancel'},{text:'삭제',style:'destructive',onPress:action}]);return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={[styles.content,{backgroundColor:colors.background}]}><Stack.Screen options={{title:'휴지통'}}/><ThemedText variant="largeTitle">휴지통</ThemedText><ThemedText variant="subhead" style={{color:colors.secondaryText}}>삭제한 기록은 복원하거나 영구 삭제할 수 있어요.</ThemedText>{deletedMemories.map(item=><View key={`m-${item.id}`} style={[styles.row,{backgroundColor:colors.surface}]}><View style={styles.copy}><ThemedText variant="headline">{item.title}</ThemedText><ThemedText variant="caption" style={{color:colors.secondaryText}}>Memory · 삭제 {new Date(item.deletedAt).toLocaleDateString('ko-KR')}</ThemedText></View><PressableScale onPress={()=>restoreMemory(item.id)}><Ionicons name="arrow-undo-outline" size={21} color={colors.text}/></PressableScale><PressableScale onPress={()=>confirm(item.title,()=>permanentlyDeleteMemory(item.id))}><Ionicons name="trash-outline" size={20} color={colors.secondaryText}/></PressableScale></View>)}{deletedVisits.map(item=><View key={`v-${item.id}`} style={[styles.row,{backgroundColor:colors.surface}]}><View style={styles.copy}><ThemedText variant="headline">방문 기록</ThemedText><ThemedText variant="caption" style={{color:colors.secondaryText}}>Visit · 삭제 {new Date(item.deletedAt).toLocaleDateString('ko-KR')}</ThemedText></View><PressableScale onPress={()=>restoreVisit(item.id)}><Ionicons name="arrow-undo-outline" size={21} color={colors.text}/></PressableScale><PressableScale onPress={()=>confirm('방문 기록',()=>permanentlyDeleteVisit(item.id))}><Ionicons name="trash-outline" size={20} color={colors.secondaryText}/></PressableScale></View>)}{!deletedMemories.length&&!deletedVisits.length?<View style={[styles.empty,{backgroundColor:colors.surface}]}><Ionicons name="checkmark-circle-outline" size={30} color={colors.tertiaryText}/><ThemedText variant="headline">휴지통이 비어 있어요</ThemedText><ThemedText variant="caption" style={{color:colors.secondaryText}}>삭제한 추억과 방문이 여기에 표시됩니다.</ThemedText></View>:null}</ScrollView>}
const styles=StyleSheet.create({content:{padding:spacing.ml,paddingBottom:spacing.xxxl,gap:spacing.sm},row:{padding:spacing.md,borderRadius:radius.md,flexDirection:'row',alignItems:'center',gap:spacing.md},copy:{flex:1,gap:4},empty:{padding:spacing.xl,borderRadius:radius.md,alignItems:'center',gap:spacing.sm,marginTop:spacing.xl}});
