import Ionicons from '@expo/vector-icons/Ionicons';
import { ActivityIndicator, ScrollView, StyleSheet, View } from 'react-native';
import { BrandLogo } from '@/components/brand-logo';
import { PressableScale } from '@/components/pressable-scale';
import { ThemedText } from '@/components/themed-text';
import { radius, shadow, spacing, useTraceTheme } from '@/theme';

export function OnboardingStep({ step, title, body, icon, tone = 'warm', action, actionLabel, secondary, loading = false }: { step: string; title: string; body: string; icon: keyof typeof Ionicons.glyphMap; tone?: 'warm' | 'lavender'; action: () => void; actionLabel: string; secondary: () => void; loading?: boolean }) {
  const { colors } = useTraceTheme();
  const tint = tone === 'lavender' ? colors.lavender : colors.warmSoft;
  const iconColor = tone === 'lavender' ? '#756BC2' : colors.warm;
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={[styles.content, { backgroundColor: colors.background }]}><View style={styles.step}><ThemedText variant="caption" style={styles.stepText}>{step}</ThemedText><View style={styles.dots}>{[0, 1, 2].map((index) => <View key={index} style={[styles.dot, { backgroundColor: index === Number(step.charAt(0)) - 1 ? colors.accent : colors.border }]} />)}</View></View><View style={styles.body}><View style={[styles.visual, { backgroundColor: tint, boxShadow: shadow.soft }]}><View style={[styles.iconCircle, { backgroundColor: colors.surface }]}><Ionicons name={icon} size={34} color={iconColor} /></View><BrandLogo size={86} style={styles.logo} /><View style={[styles.traceLine, { backgroundColor: iconColor }]} /></View><ThemedText variant="screenTitle">{title}</ThemedText><ThemedText variant="body" style={{ color: colors.secondaryText }}>{body}</ThemedText></View><View style={styles.actions}><PressableScale disabled={loading} onPress={action} style={[styles.cta, { backgroundColor: colors.accent, boxShadow: shadow.cta }]}>{loading ? <ActivityIndicator color={colors.onAccent} /> : <><ThemedText variant="headline" style={{ color: colors.onAccent }}>{actionLabel}</ThemedText><Ionicons name="arrow-forward" size={18} color={colors.onAccent} /></>}</PressableScale><PressableScale disabled={loading} onPress={secondary} style={styles.secondary}><ThemedText variant="subhead" style={{ color: colors.secondaryText }}>나중에 하기</ThemedText></PressableScale></View></ScrollView>;
}
const styles = StyleSheet.create({ content: { flexGrow: 1, padding: spacing.ml, paddingTop: spacing.lg, paddingBottom: spacing.xxl, justifyContent: 'space-between', gap: spacing.xl }, step: { alignItems: 'center', gap: spacing.xs }, stepText: { color: '#756BC2' }, dots: { flexDirection: 'row', gap: 5 }, dot: { width: 5, height: 5, borderRadius: radius.full }, body: { gap: spacing.md }, visual: { height: 290, borderRadius: radius.lg, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', gap: spacing.sm }, iconCircle: { width: 76, height: 76, borderRadius: radius.full, alignItems: 'center', justifyContent: 'center', zIndex: 2 }, logo: { position: 'absolute', right: 38, bottom: 34, opacity: 0.92 }, traceLine: { width: 170, height: 3, borderRadius: radius.full, transform: [{ rotate: '-16deg' }], opacity: 0.45 }, actions: { gap: spacing.xs }, cta: { minHeight: 56, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: spacing.xs }, secondary: { minHeight: 46, alignItems: 'center', justifyContent: 'center' } });
