import { useEffect, useRef } from 'react';
import { StyleSheet, View } from 'react-native';
import * as maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import { ThemedText } from '@/components/themed-text';
import type { Coordinates } from '@/types/trace';
import type { MapVisitPin, RoutePoint } from '@/types/location';

type TraceMapProps = { pins: MapVisitPin[]; selectedId?: string; onSelect: (pin: MapVisitPin) => void; fitKey?: number; currentLocation?: Coordinates | null; routePoints?: RoutePoint[]; exploration?: boolean };
const KOREA: [number, number] = [127.75, 36.25];
const mapStyle = process.env.EXPO_PUBLIC_MAPTILER_KEY ? `https://api.maptiler.com/maps/streets-v2/style.json?key=${process.env.EXPO_PUBLIC_MAPTILER_KEY}` : null;

export function TraceMap({ pins, selectedId, onSelect, fitKey = 0, currentLocation, routePoints = [], exploration = false }: TraceMapProps) {
  const element = useRef<HTMLDivElement>(null); const map = useRef<maplibregl.Map | null>(null); const pinsRef = useRef<MapVisitPin[]>(pins);
  useEffect(() => { pinsRef.current = pins; }, [pins]);
  useEffect(() => { if (!element.current || !mapStyle) return; const instance = new maplibregl.Map({ container: element.current, style: mapStyle, center: KOREA, zoom: 6.3, minZoom: 5, maxZoom: 18, attributionControl: {} }); instance.addControl(new maplibregl.NavigationControl({ visualizePitch: false }), 'bottom-right'); instance.on('load', () => { instance.addSource('trace-places', { type: 'geojson', data: { type: 'FeatureCollection', features: [] }, cluster: true, clusterMaxZoom: 10, clusterRadius: 52 }); instance.addSource('trace-route', { type: 'geojson', data: { type: 'Feature', properties: {}, geometry: { type: 'LineString', coordinates: [] } } }); instance.addLayer({ id: 'trace-route-line', type: 'line', source: 'trace-route', layout: { 'line-cap': 'round', 'line-join': 'round' }, paint: { 'line-color': '#D97757', 'line-width': ['interpolate', ['linear'], ['zoom'], 5, 2, 12, 5], 'line-opacity': 0.72 } }); instance.addLayer({ id: 'clusters', type: 'circle', source: 'trace-places', filter: ['has', 'point_count'], paint: { 'circle-color': '#171717', 'circle-radius': ['step', ['get', 'point_count'], 20, 20, 25, 80, 31], 'circle-stroke-color': '#F7F3EA', 'circle-stroke-width': 2 } }); instance.addLayer({ id: 'cluster-count', type: 'symbol', source: 'trace-places', filter: ['has', 'point_count'], layout: { 'text-field': '{point_count_abbreviated}', 'text-font': ['Open Sans Bold'], 'text-size': 12 }, paint: { 'text-color': '#FFFFFF' } }); instance.addLayer({ id: 'trace-point', type: 'circle', source: 'trace-places', filter: ['!', ['has', 'point_count']], paint: { 'circle-color': '#F7F3EA', 'circle-radius': ['interpolate', ['linear'], ['zoom'], 6, 5, 10, 8, 14, 14], 'circle-stroke-color': '#171717', 'circle-stroke-width': 2 } }); instance.on('click', 'clusters', (event: maplibregl.MapMouseEvent) => { const feature = instance.queryRenderedFeatures(event.point, { layers: ['clusters'] })[0]; const clusterId = feature?.properties?.cluster_id; const source = instance.getSource('trace-places') as maplibregl.GeoJSONSource; if (typeof clusterId === 'number') source.getClusterExpansionZoom(clusterId).then((zoom: number) => instance.easeTo({ center: (feature.geometry as GeoJSON.Point).coordinates as [number, number], zoom })); }); instance.on('click', 'trace-point', (event: maplibregl.MapLayerMouseEvent) => { const id = event.features?.[0]?.properties?.placeId; const pin = pinsRef.current.find((item) => item.placeId === id); if (pin) onSelect(pin); }); instance.on('mouseenter', 'clusters', () => { instance.getCanvas().style.cursor = 'pointer'; }); instance.on('mouseleave', 'clusters', () => { instance.getCanvas().style.cursor = ''; }); }); map.current = instance; return () => { instance.remove(); map.current = null; }; }, [onSelect]);
  useEffect(() => { const source = map.current?.getSource('trace-places') as maplibregl.GeoJSONSource | undefined; if (!source) return; source.setData({ type: 'FeatureCollection', features: pins.map((pin) => ({ type: 'Feature', properties: { placeId: pin.placeId, title: pin.title, visitCount: pin.visitCount }, geometry: { type: 'Point', coordinates: [pin.longitude, pin.latitude] } })) }); }, [pins]);
  useEffect(() => { const source = map.current?.getSource('trace-route') as maplibregl.GeoJSONSource | undefined; if (!source) return; source.setData({ type: 'Feature', properties: {}, geometry: { type: 'LineString', coordinates: exploration ? routePoints.map((point) => [point.longitude, point.latitude]) : [] } }); }, [exploration, routePoints]);
  useEffect(() => { const pin = pins.find((item) => item.placeId === selectedId); if (pin) map.current?.easeTo({ center: [pin.longitude, pin.latitude], zoom: 13, duration: 460 }); }, [pins, selectedId]);
  useEffect(() => { if (!fitKey || !map.current || !pins.length) return; const bounds = new maplibregl.LngLatBounds(); pins.forEach((pin) => bounds.extend([pin.longitude, pin.latitude])); map.current.fitBounds(bounds, { padding: 64, maxZoom: 13, duration: 520 }); }, [fitKey, pins]);
  useEffect(() => { if (currentLocation) map.current?.easeTo({ center: [currentLocation.longitude, currentLocation.latitude], zoom: 14, duration: 460 }); }, [currentLocation]);
  if (!mapStyle) return <View style={styles.missing}><ThemedText variant="headline">웹 지도 키가 필요해요</ThemedText><ThemedText variant="caption">EXPO_PUBLIC_MAPTILER_KEY를 설정하면 전국 지도를 탐색할 수 있어요.</ThemedText></View>;
  return <View style={styles.root as never} nativeID="trace-web-map"><div ref={element} style={{ width: '100%', height: '100%' }} /></View>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, missing: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, gap: 8 } });
